// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantOnline.DatabaseContext;

#nullable disable

namespace RestaurantOnline.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20231018171750_InitializeCartInDatabase")]
    partial class InitializeCartInDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantOnline.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("RestaurantOnline.Models.MenuPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("MenuPosition");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9bf0f18-9751-43cf-b186-37ca5f95ec31"),
                            Description = "Most popular salat on the world",
                            Name = "Cesar Salat",
                            Price = 25.0
                        },
                        new
                        {
                            Id = new Guid("13757aac-0114-4f18-b8ed-f5c934d81326"),
                            Description = "Most popular pasta on the world",
                            Name = "Spaghetti",
                            Price = 31.0
                        },
                        new
                        {
                            Id = new Guid("f41ff707-8f33-4e1b-88b2-2991e7ab84a4"),
                            Description = "Simple pasta with eggs, bacon and parmeggiano",
                            Name = "Carbonara",
                            Price = 28.0
                        },
                        new
                        {
                            Id = new Guid("e3ab842b-87f8-4ff2-ab7a-0fb9378484b8"),
                            Description = "Soft drink",
                            Name = "Coca-cola",
                            Price = 5.0
                        },
                        new
                        {
                            Id = new Guid("0bd92575-4981-4020-8c7f-e539a5937952"),
                            Description = "Beer",
                            Name = "Johannes",
                            Price = 7.0
                        });
                });

            modelBuilder.Entity("RestaurantOnline.Models.MenuPosition", b =>
                {
                    b.HasOne("RestaurantOnline.Models.Cart", null)
                        .WithMany("ToOrder")
                        .HasForeignKey("CartId");
                });

            modelBuilder.Entity("RestaurantOnline.Models.Cart", b =>
                {
                    b.Navigation("ToOrder");
                });
#pragma warning restore 612, 618
        }
    }
}
